package org.example.recipify_back.entity.enumEntity;

public enum IngredientCategory {
    VIANDE,
    FRUITS_DE_MER_ET_POISSONS,
    LEGUME,
    FRUIT,
    PRODUIT_LAITIER,
    CEREALE,
    EPICE_ET_AROMATE,
    HUILE_ET_GRAISSE,
    SAUCE_ET_CONDIMENT,
    SUCRE_ET_EDULCORANT,
    FRUIT_A_COQUE_ET_GRAINE,
    LEGUMINEUSE,
    BOISSON,
    ALCOOL,
    PRODUIT_FERMENTE,
    PRODUIT_TRANSFORME,
    FARINE_ET_AMIDON,
    ADDITIF_ET_AGENT_DE_LEVEE,
    SUBSTITUT_ALIMENTAIRE,
    AUTRE
}

